### ISSUE TITLE
Running the test suite randomly fails on requirements.

### ISSUE THREAD

**Issue by Bjeaurn** [monounity/karma-typescript#108]
We've seen this in our local project, the unit tests work normally most of the time. But every now and again, an error like underneath is thrown and the tests don't run.

We've seen this on continuous integration (CircleCI) as well. Most of the time it runs fine, sometimes it randomly crashes causing failed builds that should be fine.

```
Chrome 56.0.2924 (Mac OS X 10.12.3) ERROR
  Uncaught reflect-metadata shim is required when using class decorators
  at /var/folders/ng/2bsj5gmn4tj8dl8mn9vcygk00000gp/T/karma-typescript-bundle-70115HWfqnW7bcUXO.js:1307
```

Is there anything that I can help to debug what's causing this? Or is this a known issue?

**Comment by erikbarke** [comment]
Hey @Bjeaurn, it sounds like the some bundled code sometimes gets executed before the `reflect-metadata` shim has loaded which can be solved in several ways, depending on how/when you load the `reflect-metadata` shim.

For example, the [Angular2 example](https://github.com/monounity/karma-typescript/tree/master/examples/angular2) loads `base.spec.ts` first of all in the Karma config `files` section, and `base.spec.ts` imports `core-js` at the top, making sure `core-js` (which polyfills the same stuff as `reflect-metadata`) is loaded before anything else.

Also, the Angular2 example uses the bundler option `karmaTypescriptConfig.bundlerOptions.entrypoints` which is a filter for which files in the bundle should get executed by the commonjs bridge.

By default `karma-typescript` executes *all* Typescript files specified in the Karma config `files` section, in the order they were added. Sometimes this isn't the desired behavior since this could mean that application code is executed before the unit test has finished setting up the test environment, so filtering out just the spec files `karmaTypescriptConfig.bundlerOptions.entrypoints` makes sure the commonjs bridge executes the tests before anything else.

**Comment by erikbarke** [comment]
Were you able to sort this issue out?
