### ISSUE TITLE
Ignore Type Script Errors

### ISSUE THREAD

**Issue by premranderia** [monounity/karma-typescript#115]
I am trying to migrate our angular 1.5 project to 2. We have over 2000 spec files and after running karma-typescript on them, I get tons of typescript errors. 
Is there any config where karma does not **fail** for typescript errors and just **warns** about them ?

**Comment by erikbarke** [comment]
Hey @premranderia, a couple of questions:
- Does your project compile without errors with `tsc`?
- What kind of errors are you getting? Are they caused by syntax errors in your code and/or caused by missing/duplicate/outdated typings?
- Is the option `noEmitOnError` set in your `tsconfig.json` or in `karmaTypescriptConfig.compilerOptions`?

**Comment by premranderia** [comment]
@erikbarke 
1) No there are 22K type script error in my project. As I mentioned we are in process of migration.
2) Errors are Type Error
eg: In .spec.ts we have mocked some angular providers an ts complains that you cannot use classes without **new**
class MockProvider {}
$provide.value('MockProvider', MockProvider);
3) npEmitOnError: false which is the default so I have not included in my project

I ended up resolving these errors and finally it compiles and tests passes.
Thanks
