### ISSUE TITLE
Resolve path for import .json file 

### ISSUE THREAD

**Issue by netzzwerg** [monounity/karma-typescript#133]
Hello, again the example is running here: https://github.com/netzzwerg/typescript-webpack-karma-mocha. 

In the `src/index.ts` file there is an working .json file import:
 `import * as foo from './foo.json'; `

If I want to move the .json file to the root folder and change the import like this:  `import * as foo from '../foo.json'; ` this still works but for this  `import * as foo from 'foo.json'; ` i get a cannot find module error. For .ts files, this would be not a problem but for .json files, the resolver seems to be broken.

Thank you!

**Comment by erikbarke** [comment]
As far as I can tell you're using the default module resolution, which [mimics the module resolution strategy of Node.js](https://www.typescriptlang.org/docs/handbook/module-resolution.html). This means that Typescript will look for non-relative imports such as `'foo.json'` in `node_modules`. To make this import work it has to be relative, ie begin with a dot or a slash.

The obvious exception to this is path mapping, which you're using for importing `'dom'`, but path mapping only works for `.ts` and `.tsx` files, as far as I know.

Please note that karma-typescript only supports the "Node" module resolution, since "Classic" has been more or less abandoned by Typescript and now exists mostly for backward compatibility.
