### ISSUE TITLE
integration with proxyquire

### ISSUE THREAD

**Issue by ChristophAtAdlos** [monounity/karma-typescript#137]
Is there a simple way to integrate [proxyquire](https://github.com/thlorenz/proxyquire) resp. [proxyquireify](https://github.com/thlorenz/proxyquireify) with karma-typescript?   

Or are there other ways to make private/protected class properties and private/protected class methods accessible for testing purposes?

**Comment by erikbarke** [comment]
Have you tried casting to `any`?

```javascript
let component = new Component();
(<any> component).somePrivateThingy
```

**Comment by ChristophAtAdlos** [comment]
no, I did not try it yet. In the meantime, I extended the class by public getters and bindings:   

```javascript

class MockMyClass extends MyClass{
    public testMethodOne = this.privateMethodOne.bind(this);
    public testMethodTwo = this.privateMethodTwo.bind(this);

    public get testConfig() {
        return this._config;
    }
}
testClass = new MockMyClass();
describe("Test MyClass", () => {
    it("Calls privateMethodOne", () => {
        spy = sandbox.spy(testClass, "testMethodOne");
        testClass.doSomethingPublicWhatInvokesThePrivateMethod();
        expect(spy.called).to.be.true;
    });
});
```
This works well for me, but I don't know about side effects.

**Comment by erikbarke** [comment]
If it solves your problem, go for it. Personally, I wouldn't access private members in a unit test because I think it breaks encapsulation and defeats the purpose of having private and public accessors, but the [jury's still out](https://stackoverflow.com/questions/105007/should-i-test-private-methods-or-only-public-ones) on whether testing private functions is good or bad practice, you decide!
