### ISSUE TITLE
How do I use mock-require with karma-typesciprt

### ISSUE THREAD

**Issue by FreshRob** [monounity/karma-typescript#146]
I was wondering if you could help with getting mock-require to work.

I have seen it in your tests but I am unable to do it myself as I get the following error.
I am unsure as to whether if it an effect of the typescript bundle 

> Uncaught TypeError: Module._resolveFilename is not a function

concept of what I am trying to achieve below

**depa.ts**

> export
 const getRunner = ()=> { return "peter"} ;`

**depb.ts**
>import {getRunner } from './depb'
export const getResult = ()=> { return getRunner();}

**depb.spec.ts**
>import * as mock from "mock-require"; 
mock("./depa", {getRunner : ()=> { return "simon"}});
import {getResult} from "./depb";
expect(getResult()).to.be("simon");

**Comment by erikbarke** [comment]
Hey @FreshRob, I'm fairly certain this won't work at all because `mock-require` is meant to be run in a real Node.js environment, it requires the core module system and even uses undocumented functions in the internal API of Node.js.

Karma-typescript runs in a web browser, emulating the Node.js environment (the same way Browserify does) by serving browser shims for Node.js builtin modules like `os` and `path` etc.

Some of these builtins don't make sense in a browser, like for instance the module system mentioned above. The module system can be emulated using, for instance, CommonJS with bundlers like Browserify or Webpack (or the builtin bundler in karma-typescript).

The karma-typescript project is mostly tested with integration tests, but a few select areas are tested using pure unit tests. These unit tests are run with [tape](https://github.com/substack/tape) which runs in Node.js, allowing the tests to use `mock-require`, hope this helps.

**Comment by FreshRob** [comment]
Hi @erikbarke , Thank you for your words of advise. I now see the rabbit hole I got lost in, and the part of the readme I closed over.

My solution in the end was to create a proxy on your implementation of commonJs to expose the internal dependencies to all me to spy on them.

**Comment by erikbarke** [comment]
Ooh, that proxy could probably be useful for other users 😃  Would you like to share the actual code, or some kind of example here?

**Comment by FreshRob** [comment]
@erikbarke my solution was super dirty and hacky. The ideal solution would be to add module in commonjs to the global scope and create a function which can be called inside of the test to mock a module.

If I get time tonight I will look into how implement it if it was part of karma-typescript

Here is the hacky code

file before all tests run (Using new promise to wrap global.wrappers)
> (function (global) {
    const fn = 0, map = 2, id = 1;
    global.__internal_modules__ = {}
    let currentWrappers = global.wrappers;
    global.wrappers = new Proxy(currentWrappers, {
        set: (target, filename, wrapper) => {
            if (!wrapper || filename.indexOf('spec') != -1 || filename.indexOf('src/') == -1) {
                target[filename] = wrapper;
                return;
            };
            let module = { exports: {}, id: wrapper[id], uri: filename };
            wrapper[fn].call(module.exports, (dep) => {
                var i = global.wrappers;
                var z = global.__internal_modules__;
                return z[dep.replace("./", "src/") + ".ts"];
            }, module, module.exports, filename.slice(0, filename.lastIndexOf("/")), filename);
            wrapper[fn] = function (a, module) {
                module.exports = global.__internal_modules__[wrapper[id]];
            };
            global.__internal_modules__[wrapper[id]] = module.exports
            target[filename] = wrapper;
        }
    })
})(this)

**Mock func**
> export const mockModule= (name: string, method: string, mockValue: any) => {
    var original, filename = name.replace("./", "src/") + ".ts"
    var internalDependecies;
    beforeEach(()=>{
        internalDependecies =  = (<any>window).__internal_modules__;
        original = internalDependecies[filename][method];
        internalDependecies[filename][method] = mockValue;
    });
    afterEach(() => {
        internalDependecies[filename][method] = original;
    })
}

in tests
> mockModule("./window.document", "document", {}});

**Comment by erikbarke** [comment]
PR please 😃
