### ISSUE TITLE
Enhance testing process

### ISSUE THREAD

**Issue by gempain** [monounity/karma-typescript#195]
See #193 for background. 

We should probably:

* Add a build script as part of the test workflow, because it currently needs to be ran separately. Some users (like I) may be disturbed when they run tests and don't see their changes applied.
* Add an npm script that allows users to reproduce tests ran on CI servers, so that they can test locally before pushing.
* Change the unit test framework and move to Jasmine. It's easier to understand, more intuitive, and better supported (opinion based).

All the best :smile:

**Comment by erikbarke** [comment]
First of all, I think this issue is as much about improving the workflow as it is about adding more documentation for contributors ☺️

Secondly, sorry for the wall of text...

## Scripts
These are the npm scripts in the root package.json as of now:

Name | Command | Description
------ | ------|-------------
build | `tsc --rootDir ./src`| Compile the source code once
build:watch | `tsc -w --rootDir ./src` | Compile the source code and watch for changes
lint | `eslint ./lib/*.js && tslint --project tsconfig.json`| Lint all sourcecode
test | ./ci/run.sh | Run all integration tests and most of the example projects (**unix**),
test:unix | `./ci/install.sh && ./ci/run.sh` | Install all integration projects/example projects and run all tests (**unix**)
test:windows | `.\\ci\\install.bat & .\\ci\\run.bat` | Install all integration projects/example projects and run all tests (**windows**)
test:unit | `tape dist/**/*.spec.js \| faucet`| Run the unit tests

In the `package.json` of each example project and each integration test project there's an npm script called `dev` which calls a gulp script in the root project, `gulpfile.js`. This gulp script copies the compiled files of karma-typescript into the node_modules folder of the example or integration project, (which is a heck of a lot faster than installing karma-typescript with "npm i ../") before running the tests with Karma.

Up until now I've kept a second command line tab running with `npm run build:watch` and then I develop/go bug hunting in one of the example projects because they're small and execute way faster than the integration projects. Whenever I've made a change to the source code I just rerun `npm run dev`.

This is a quite simple workflow IMHO; run `npm run build:watch`, choose a project to work on and run `npm run dev` as needed and all the grunt (haha...) work will be taken care of.

If we are going to simplify this even more and add `npm run build` as a step I think it should be both platform independent and work for all `npm run dev` scripts and the root `npm test` script.

Regarding a new *run-everything-before-push* script it will be fairly simple: `npm run build && npm run lint && npm run test` but what should we call it? `npm run prepush`? `npm run build:all`?

The commands `test:unix` and `test:windows` aren't used on the build servers and I rarely use them locally, so we could unceremoniously just remove them.

## Unit tests
Ironically, I chose [tape](https://github.com/substack/tape) because I thought it was so easy to use with its simple API and less setup compared to Jasmine... It's a simplistic but solid little framework, I would give it another go before dismissing it completely ☺️

**Comment by mitchhentges** [comment]
Thanks for the writeup :)

I find that most projects usually have their `test` script automatically deal with building. For example, everything that depends on `karma-typescript` just run `npm test`, and the build is performed by `karma` when it invokes its plugins (such as `karma-typescript` :wink:).

> Regarding a new run-everything-before-push script it will be fairly simple: npm run build && npm run lint && npm run test but what should we call it? npm run prepush? npm run build:all?

I've found that `npm run ci` works nicely to handle that case.

Using `npm run build:watch` and then using the example projects sounds like a swell workflow, we'd just need to document it in a more visible location.

I'm personally happy with `tape`, lightweight is nice :)

**Comment by erikbarke** [comment]
The example projects serve two purposes, they serve both as working examples and as a kind of integration tests when executed on the ci servers. This was the main reason for splitting the example project test commands into `npm run dev` and `npm test`; the former requires a full install of the karma-typescript root project to work and the latter only requires a local `npm install`for the user to be able to run the example.

**Comment by gempain** [comment]
Sorry for the delay;

I'll agree with the `npm run ci`.

As for `tape` I'll give it a try :)

As for the platform-dependent tests, I think we could simplify the scripts a little bit. For example, instead of having `test:windows` and `test:unix`, we could write a simple Node script that deals with that kind of problem. There may also be node packages that deal with this issue. I will agree that doing so will hide the actual scripts ran inside that little Node script, making it harder to understand what they do.

**Comment by erikbarke** [comment]
Ok, `npm run ci` it is!

Do you wanna take a shot at implementing your idea of a test script that builds the project before running the tests, @gempain? Maybe we could just add a build task to the gulp file?

I've removed `test:windows` and `test:unix` now, they only ran scripts in the ./ci directory anyway and had somewhat misleading names, so good riddance 😌

Also, here are the [contributing guidelines](https://github.com/monounity/karma-typescript/wiki/Contributing), let me know what's missing and what needs improvement.

**Comment by erikbarke** [comment]
I've added a couple of PRs now that should cover what we've discussed here: #204, #205, #206!

**Comment by gempain** [comment]
@erikbarke just read the contributing file, and it looks sport perfect :)

For the build, do you still need me to implement something ? I am a bit busy at the moment and can't promise to react quickly :smile: Adding this platform independent build can definitely be done in the gulp file as it's usually where you'd find such scripts :)

I think that with all the recent changes, things look much better :) Love collaborative work :smiley:

**Comment by erikbarke** [comment]
Everything has been implemented, so if you guys are happy with the changes I'll merge the PRs!

**Comment by gempain** [comment]
Approved :)

**Comment by erikbarke** [comment]
Ok, all PR:s are merged now, closing ☺️
