### ISSUE TITLE
Remove shims.ts

### ISSUE THREAD

**Issue by mitchhentges** [monounity/karma-typescript#212]
Hmm, do you think we can remove [shims.ts](https://github.com/monounity/karma-typescript/blob/53a9700b734de2063b5c69c0cd8ca6cbd3fb3631/src/bundler/resolve/shims.ts)?
Arguably, it makes it easier for newcomers, but IMHO, it makes `karma-typescript` more confusing:

So long as projects use shims which are in `karma-typescript`, it will work out-of-box. The user will be under the impression that somehow, `karma-typescript` magically manages (all?) shims. Once they start to need their first shim that isn't defined in `karma-typescript`, it will be confusing - how was it working before? Why is the new shim special? How do they make it work _now_?

Just my 2c, but interested to learn more about it :)

**Comment by erikbarke** [comment]
These shims emulate the Node.js environment, just like in [browserify](https://github.com/browserify/browserify/blob/master/lib/builtins.js), and the shims [are used](https://github.com/monounity/karma-typescript/blob/master/src/bundler/resolve/resolver.ts#L173) by [browser-resolve](https://github.com/defunctzombie/node-browser-resolve) if `karmaTypescriptConfig.bundlerOptions.addNodeGlobals` is set to a truthy value.

If we remove this feature we would probably have to add a setting where users could provide their own list of shims and it would be a breaking change for (I'm guessing here) quite a few users, so I don't think this would be easy to remove...

On a side note, `karmaTypescriptConfig.bundlerOptions.addNodeGlobals` should probably be renamed to `karmaTypescriptConfig.bundlerOptions.emulateNodeEnvironment` or similar.

**Comment by mitchhentges** [comment]
Hmm, interesting! It sounds like `shims.ts` handles the situation where code that is expected to run in Node.js is tested in `karma`, which runs code in browsers. So, the Node.js environment has to be recreated/mocked in the browser so the code will still run.
Two questions:
* If code is meant for Node.js (and not to be executed in browsers), should it really be executed in `karma`, whose mission statement is "A simple tool that allows you to execute JavaScript code in multiple *real browsers.*"? IMHO, such code should be tested in the Node.js environment that it is expected to run in (such as with [`mocha`](https://github.com/mochajs/mocha) or [`jest`](https://github.com/facebook/jest))
* More importantly, even if a developer wants to emulate a Node.js in the browser, I'm not sure that `karma-typescript` should handle shims. Yes, there probably _should_ be a karma plugin that supports that usecase, but for the sake of "doing one thing and doing it super-duper well", I don't think that handling shims should land in `karma-typescript`'s jurisdiction.

**Comment by erikbarke** [comment]
A lot of users are running `webpack` or `browserify` side by side with `karma-typescript` and since all the big bundlers are able to bundle an emulated Node.js environment I really think that the `karma-typescript` bundler should provide at least the same level of functionality. Removing the shims would not only alienate some existing users but it would also probably generate issues asking "I can do this with webpack for my live bundle, why doesn't it work with karma-typescript?".
The point of `karma-typescript` imho is to make the testing process as seamless as possible, it shouldn't matter which bundler you're using for production or how you're using it.

Having said that, the built-in bundler is an attempt at marrying "the Karma way" of serving single files to the browser with bundling modules from `node_modules`. Although being quite simplistic or even naive compared to more sophisticated bundlers the bundler is (kind of) feature complete with its own little plugin API and, *goddangit*, it does its job. The one thing that irks me with it is that while trying to honor the Karma way of doing stuff I have more or less reinvented the wheel when there already exist more mature bundlers out there, supported by huge communities.

So I have been toying on and off with the idea of scrapping the built in bundler and replacing it with `browserify`... This would be a breaking change but all the existing functionality and more would still be available to users. It would also solve issues like #176 and #163 and in the long run probably generate fewer issues and feature requests...

**Comment by mitchhentges** [comment]
Hmm, makes sense.
I suppose it comes down to what the scope of `karma-typescript` should be. IMHO, `karma-typescript` should strictly act as a `typescript` processor, and should leave related jobs to the rest of the ecosystem, such as bundling and (potentially) even coverage reporting.

I understand that it would be ideal for `webpack` users to have a minimum amount of work to do to have their code that's compiled by webpack for production to be easily compiled with `karma` and `karma-typescript` for testing. However, for that specific case, wouldn't something like [karma-webpack](https://github.com/webpack-contrib/karma-webpack) allow those users to have the least work required to have their code working in tests?

I completely agree that if we remove shims, we'd have to provide a good migration path, because it will be a _massive_ breaking change for many users. This might be a very difficult problem to solve, but I don't think that it's a reason to avoid simplifying `karma-typescript`

**Comment by erikbarke** [comment]
I had a project which used webpack and I was, to put it mildly, a bit put off by how complicated it was to get Karma + webpack to compile the Typescript code, run the tests and generate accurate remapped coverage with lines that wasn't off by one or more... So I decided to scratch my itch and created `karma-typescript` with essentially one goal in mind: as simple config as possible and I think that should be the goal in the future too.

If we're talking about narrowing the scope of this package, maybe `karma-typescript` could the be "mothership" and stuff like bundling and coverage are left completely to `browserify`/`webpack` (how about we make the bundler pluggable?) and `nyc` while `karma-typescript` provides a simple configuration interface to tie everything nicely together?

There are a handful of plugins that would have to be deprecated, most are authored by me but there are also at least one third party plugin out there. Stuff like es6 support and "angular template path transformations" could probably be handled by the third party bundler. 

Also, when upgrading from  `istanbul` to `nyc` we get built-in source map support which means we no longer have to rely on the `remap-istanbul` package, so maybe that could be a good place to start digging.

One way to make a transition like this would be to not transition at all ☺️ We continue maintaining the 3.x series with its current tool chain and plugins and whatnot and release all the new and shiny stuff as a 4.x series, just a thought.

**Comment by mitchhentges** [comment]
Interesting! I can definitely see the value to having one plugin with simple config to fully meet the requirements of most projects.
I think that the naming of this package might not be 100% accurate in that case, since it's not strictly acting as a `typescript` compiler, but rather as a complete solution to existing projects that want a simple, monolithic solution to the testing problem.
Makes sense though! I'll close the issue :)
