### ISSUE TITLE
karma-typescript/example-project/ Fails

### ISSUE THREAD

**Issue by phurst** [monounity/karma-typescript#24]
[log.txt](https://github.com/monounity/karma-typescript/files/586027/log.txt)

See the attached log file. 
The cause is missing dependent modules, starting with 'browser-resolve'.
I was able to get it working by doing the following npm installs. It would be helpful to include these steps in the instructions.

$ npm install --save-dev browser-resolve
$ npm install --save-dev detective
$ npm install --save-dev buffer
$ npm install --save-dev process

**Comment by monounity** [comment]
@phurst, what os are you on and which versions of npm and nodejs are you using? These packages get pulled in automatically in my tests on

```
* osx 10.11.6
* nodejs 6.4.0
* npm 3.10.3
```

and on

```
* windows 10
* nodejs 4.2.1
* npm 3.5.3
```

This could be [an npm bug](https://github.com/npm/npm/issues/10727), does it work if you do a fresh install of karma-typescript run `npm install` twice for the example project?

**Comment by oilart** [comment]
I've faced the same issue on `OSX 10.11.3` Node `v4.2.6` and npm `2.14.12`.

**Comment by monounity** [comment]
@oilart, did running `npm install` twice solve the problem? If enough people encounter this problem I guess I'll have to swallow the bitter pill and start including these dependencies explicitly in package.json for the plugin or even worse, the package.json for the example projects. I'm a bit hesitant doing so because this really is the job of the package manager, but if the package manager doesn't, well, manage the packages, we'll have do it ourselves...

**Comment by oilart** [comment]
@monounity running `npm install` twice didn't solve the problem. Tried a clean run - no luck. Seems like those dependencies should be added. Thanks.

**Comment by TheHatSky** [comment]
I've just installed all listed browser shims as dependencies
`npm i -D assert buffer console constants crypto domain events http https os path punycode querystring stream string_decoder timers tty url util vm zlib`
and it worked.

**Comment by monounity** [comment]
So be it!
I'll add the deps, this npm bug is affecting way too many users now.
