### ISSUE TITLE
Attempts to resolve require() calls not from top level scope

### ISSUE THREAD

**Issue by devoto13** [monounity/karma-typescript#248]
- Clone [repro](https://github.com/devoto13/kt-resolve/)
- `$ yarn && yarn test` (`npm install` will probably work as well)
- Observe error: 

        Error: Unable to resolve module [./toBeObject] from [/Users/devoto13/Projects/trash/kt-resolve/node_modules/jasmine-expect/dist/jasmine-matchers.js]

It seems that karma-typescript attempts to resolve any calls to `require('<path>')` in the source code, even if they are not real require calls. Library `jasmine-expect` is bundled and bundle uses `require('<path>')` calls, but these calls are not calls to global Node `require` function, but instead calls to local `require` function passed as parameter to module functions. And it obviously fails to resolve.

You can also try with reduced test case. Go to the `src/test.ts` in the repo, comment out `import 'jasmine-expect'` and uncomment `import './another'` line.

**Comment by erikbarke** [comment]
This one is actually a bit tricky since both `jasmine-expect` and `karma-typescript` uses bundles to serve the code to the web browser running the tests... If you do an `import 'jasmine-expect'` its bundle will be bundled inside the `karma-typescript` bundle, making the `require` mechanisms of each bundle clash with each other 😞

I've created a workaround by modifying the `examples/typescript-latest` project:

```bash
npm i jasmine-expect karma-jasmine-matchers
```

Add the `"jasmine-matchers"` framework to the Karma config (this will load the `jasmine-expect` matchers in the web browser):
```js
module.exports = function(config) {
    config.set({

        frameworks: ["jasmine", "jasmine-matchers", "karma-typescript"],

        files: [
            { pattern: "src/**/*.ts" }
        ],

        preprocessors: {
            "**/*.ts": ["karma-typescript"]
        },

        reporters: ["dots", "karma-typescript"],

        browsers: ["Chrome"]
    });
};
```

Copy `node_modules/jasmine-expect/jasmine-matchers.d.ts` to the root of `examples/typescript-latest`.

Modify `hello.component.spec.ts`:

```js
describe("HelloComponent", () => {

    it("should say 'Hello world!'", () => {

        let mockHelloService = new MockHelloService();
        let helloComponent = new HelloComponent(mockHelloService);

        expect(helloComponent.sayHello()).toEqual("Hello world!");

        expect([true, false]).toBeArrayOfBooleans(); // <-- try a new matcher
    });
});
```

This compiles and runs, with the drawback that you have to copy the d.ts file ☺️
If I were you I would ask the `jasmine-expect` maintainer to publish the typings as an `@types` project too, hope this helps.

**Comment by devoto13** [comment]
First of all thanks for the detailed answer. 

From the `DependencyWalker` source code it looks like it will attempt to resolve calls to any function named `require`. I think this is a very naive approach and the root cause of the problem reported here. See `./another.js` in the repro for example, it just happened that arbitrary function is called `require`, but it has nothing to do with CommonJS module. That is the thing I would like to have fixed. Maybe it is possible to perform some more advanced static analysis to prevent false positives in resolution. Otherwise putting any function called `require` causes `karma-typescript` to break. For example code below has absolutely nothing to do with CommonJS module, but will fail with the same error.

```
function test() {
  const require = (_: string) => null;
  require('test');
}
```

I know how to workaround the issue, but I would like to have a proper fix instead. Actually there was `@types` package for `jasmine-expect` published before :) but it got removed since library bundles TS type definitions now. And I was trying to get rid of two extra packages (`karma-jasmine-matchers` and `@types/jasmine-expect`) and just solve all my problem with single line `import 'jasmine-expect'`. It actually works in Angular CLI project, where tests are bundled by Webpack, so I assume doing more clever detection of `require` calls is possible.

**Comment by erikbarke** [comment]
This is getting interesting 😃 

First of all, here's a much better workaround than my first one:

```js
karmaTypescriptConfig: {
    bundlerOptions: {
        noParse: ["jasmine-expect"]
    }
}
```
When using `bundlerOptions.noParse` the `jasmine-expect` bundle just gets included in the `karma-typescript` bundle without being parsed for dependencies, with this I'm able to 

```js
import "jasmine-expect";

...

expect([true]).toBeArrayOfBooleans();
```

Regarding how the `require` statement is parsed: the bundler was heavily inspired by `browserify` and they both use the same AST parsing strategy for resolving dependencies, so doing this breaks in both bundlers:

```
function test() {
    const require = (name) => {
        console.log(name);
    };
    require("hey");
}
test();
```

The `browserify` bundler and the `karma-typescript` bundler behave this way because the `require` statement is valid anywhere, it's not like an ES6 or Typescript `import` statement that may only appear on the top level:

```js
let x;
if(true) {
    x = require("os");
}
else {
    x = require("fs");
}
console.log(x.hostname());
```

There are quite a few packages out there performing dynamic requires like in the example above or passing the require function to other functions (sinon@1.17.6 for example), so the `karma-typescript` bundler has to support at least valid Node.js applications, ie look for `require` statements anywhere.

I'm experimenting with improving the `require` statement parsing, I'll keep you posted!

**Comment by devoto13** [comment]
Thank you! `bundlerOptions. noParse` works like a charm!

Sorry about me being harsh before. Bundling is not a primary job for this project, so I think it is reasonable to expect people to add extra configuration in some corner cases. Guess I'm just spoiled by the Webpack 😆 

More clever `require` resolution would be nice for sure, but feel free to close this issue if you want. My problem is resolved now.
