### ISSUE TITLE
Call for new maintainers

### ISSUE THREAD

**Issue by erikbarke** [monounity/karma-typescript#264]
This package turned out to be way more popular than I had planned for (200+ stars and 500k+ downloads at the time of writing :rocket:) and I just can't keep up anymore.

If you are interested in maintaining/publishing this package and its plugins, please comment below.

**Comment by afterbangx** [comment]
I haven't been using this package in a few months because I haven't needed it. However, I'm about to go back to work for the company that I originally started using it with and I suspect I will be using it on a daily basis again. Are you just looking for extra help? Or are you going to be stepping away completely? I don't think I would be able to spend a ton of time helping but I could certainly contribute occasionally.
