### ISSUE TITLE
Beta 5 + latest Istanbul uses file path as directory for coverage output

### ISSUE THREAD

**Issue by erikbarke** [monounity/karma-typescript#359]
From @dwightjack:

> Hi, I tried v5.0.0-beta.0 but I encountered an unexpected behavior.
> 
> In my config, I've set up coverage reports for lconv as follows:
> 
> lcovonly: {
>   directory: 'coverage',
>   subdirectory: () => '',
>   filename: 'lcov.info',
> },
> In v4.x this was saving a coverage report to coverage/lcov.info which is one of the known paths scanned by CodeClimate.
> 
> After installing the beta version The file got saved to coverage/lcov.info/lcov.info.
> 
> Looks like istanbul is using the path generated by the configuration as a directory instead of a file path.

**Comment by erikbarke** [comment]
@dwightjack, this seems to have been fixed in 5.0.0-beta.1, does it work as expected on your end?

**Comment by dwightjack** [comment]
@erikbarke I've tried to install the 5.0.0-beta.1 version but the problem seems to be still there. The project I'm woking on is public so I've set up a demo branch:

Project: https://github.com/dwightjack/yuzu

Steps to reproduce: 

1. Checkout branch `feature/karma-ts-5`
2. `yarn`
3. run `CIRCLECI=true yarn test --browsers ChromeHeadlessCI`
4. generates a `coverage/lcov.info/lcov.info` file

Working setup:

1. Checkout `develop`
1.1 Remove `node_modules`, just in case.
2. `yarn`
3. run `CIRCLECI=true yarn test --browsers ChromeHeadlessCI`
4. generates a `coverage/lcov.info` file

Let me know if you need any other info. Thanks!

**Comment by erikbarke** [comment]
@dwightjack, I was able to reproduce the issue now, thanks ☺️ 5.0.0-beta.3 is on npm now, does it work for you?

**Comment by dwightjack** [comment]
@erikbarke works great! Thank you! 🙇

**Comment by erikbarke** [comment]
5.0.0 on npm now!
