### ISSUE TITLE
One of the nested dependencies "elliptic" has security vulnerability

### ISSUE THREAD

**Issue by tanmayghosh2507** [monounity/karma-typescript#381]
The karma-typescript package has been flagged in my organization's compliance report since the elliptic npm package that it uses, is not recommended. 

Description Provided: all versions of elliptic are vulnerable to Timing Attack through side-channels.

Hence wondering, if there is any plan to fix the vulnerability.

**Comment by erikbarke** [comment]
This is a tough one, since `elliptic` is a sub dependency:

```
karma-typescript@5.0.3
└─┬ crypto-browserify@3.12.0
  ├─┬ browserify-sign@4.2.0
    └── elliptic@6.5.2
```
And the `elliptic` dev seems to be aware of the issue but has no plans to fix it: https://github.com/indutny/elliptic/issues/128.

Removing the `crypto-browserify` isn't feasible, it would break a lot of backwards compatibility, and alternatives like `brix/crypto-js`seems to have the same vulnerability: https://github.com/brix/crypto-js/issues/88 😞
