### ISSUE TITLE
Custom typescript compiler options - paths mapping

### ISSUE THREAD

**Issue by g00fy-** [monounity/karma-typescript#4]
It may be hard - as it has to do more with commonjs - but it would be nice to be able to customize compiler options features - especially for paths mapping

``` javascript
{
  "baseUrl": "./app",
  "paths": {
    "@app/*": [
      "./*"
    ]
  }
}
```

**Comment by monounity** [comment]
Customization is always nice, could you give me an example or use case please?

**Comment by g00fy-** [comment]
In my usecase this is my `tsconfig.json`

```javascript
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "sourceMap": true,
    "strictNullChecks": false,
    "baseUrl": "./app",
    "paths": {
      "@pb/*": [
        "./*"
      ]
    },
  },
  "exclude": [
    "node_modules"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false
}
```


the `paths` option allows me to refer from file `app/cart/status.ts` to the other file in the project  in following way:

```javascript
import {Service} from '@pb/core/services'
```

instead of 
```javascript
import {Service} from '../../core/services'
```

this is something I also saw the angular team is using 
https://github.com/angular/angular/blob/master/modules/tsconfig.json#L15

**Comment by monounity** [comment]
So would having the option to pass the compiler options from tsconfig.json file to the plugin solve your problem? Something like this:

```javascript
karmaTypescript: {
    tsconfigPath: 'tsconfig.json'
}
```

**Comment by paldepind** [comment]
Being able to specify options to `tsc` would be very useful. For instance when targeting ES6 or when using other non-default settings.

**Comment by monounity** [comment]
@paldepind, custom options shouldn't be too hard to implement, it's on the list now!

**Comment by dinvlad** [comment]
Just to add a use case, it'd also be nice to be able to set `"noImplicitAny": true` so that we take full advantage of static type checking provided by Typescript. Thanks!

**Comment by monounity** [comment]
@dinvlad: This should be doable! However, due to the sequential nature of Karma (each file is sent to the preprocessor and transpiled individually), the compiler will barf on missing modules etc. To avoid this, the new compiler feature (see a4f56ad) has a list of errors to ignore, but it still catches errors like unreachable code and implicit any:s if that option is set in the config.

Also, in the upcoming 2.1 release there will be a new custom module loader (ie not depending on karma-commonjs anymore) which automatically loads modules imported from node_modules and local modules, so missing modues will be caught by the new loader.

Support for typings is still missing in the new compiler, but I expect to add that soon.

**Comment by monounity** [comment]
@paldepind: I'm thinking there should be three ways to feed options to the compiler:
* the default settings
* a tsconfig settings section in the karma config
* a path to the project tsconfig

I'm worried the project settings might make sense for developing and bundling but would break the unit test runner, so there should be a way to customize both without them interfering.

**Comment by dinvlad** [comment]
@monounity - sounds great!

Would the new compiler respect `@types` from tsconfig as well (I assume yes, since they are just regular node_modules)?

As to ignoring errors, would `suppressImplicitAnyIndexErrors: true` help in this case?

**Comment by monounity** [comment]
@dinvlad, thanks to your comment I'm now toying with the idea of compiling the whole project on karma startup :) It would allow automatic loading of typings from `node_modules/@types/`, types found in tsconfig, checking that imports exist etc. This far I haven't had any major troubles, the only thing I'm concerned about is performance, there's a lot of loading and file I/O to be done, but it's working!

**Comment by dinvlad** [comment]
Nice! Looking forward to test it on my end if you'd like.

**Comment by monounity** [comment]
Hey, sorry for late reply, but I've been banging my head against the desk over performance issues in the Typescript language service...

There's now support for compiling the whole project on karma startup in the 2.1 branch, but only for Typescript 1.8 and typings in a typings folder in the project root. I'll be adding support for @types and newer versions of Typescript soon!

Feel free to try it out :)

**Comment by monounity** [comment]
Oh, and I am not doing it the Typescript way with incremental compiling, the whole project gets compiled every time a file is changed in Karma. On large projects I'm seeing 8 million+ calls to the getScriptSnapshot function when feeding the compiler with 1000 files + 1000 accompanying unit tests, the number of calls grows exponentially with the number of files in the project. It's actually faster to just compile the whole shebang over and over than compile incrementally, I'm kind of baffled here...

**Comment by monounity** [comment]
@g00fy-, @paldepind, @pexak, @dinvlad: There is support for compiling the project on startup using the project tsconfig.json with full type checking, module loading etc in the upcoming [2.1](https://github.com/monounity/karma-typescript/tree/2.1) release. If you want to try it out you can pull in the latest from this repo in your package.json:

`"karma-typescript": "git://github.com/monounity/karma-typescript.git#2.1"`

The framework now reads the tsconfig.json by default and uses it to compile the project, more or less like the Typescript command line compiler would.

If you need different compiler options for running the tests it's possible to add/override options in the karma config:

```javascript
karmaTypescriptConfig: {
    compilerOptions: {
        sourceMap: true
    },
    reports: ...
}
```

There are examples for running unit tests with plain Typescript, angular2, react etc in the integration tests:

[Integration tests for Typescript@1.8.10](https://github.com/monounity/karma-typescript/tree/2.1/integration-tests%401.8.10)
[Integration tests for Typescript@latest](https://github.com/monounity/karma-typescript/tree/2.1/integration-tests%40latest)

A beta release for 2.1 is expected within the next week or two, you can follow progress and status in the [wiki](https://github.com/monounity/karma-typescript/wiki).

Please report any bugs you find as separate issues, that way I can keep track of everything, and give you credit in the release notes.

**Comment by dinvlad** [comment]
Excellent!

Sorry for the delay.. I've  got it working per your latest comment.

I just had to add `"suppressImplicitAnyIndexErrors": true` (in addition to the existing `"noImplicitAny": true`) to `tsconfig` to fix an indexing error for a DOM Element (I have an `element.tagName === 'DIV'` check in my spec). Maybe this error should not be ignored, but it's supposed to get the right type info from the 'dom' lib by default (https://www.typescriptlang.org/docs/handbook/compiler-options.html#--lib). Though this error has not been reported when I ran `ts-node` manually before, so it might be something to look into here.

I also needed to exclude any custom `.d.ts` files from Karma config, e.g.
```
files: [
  'src/!(*.d).ts',
],
```
Otherwise, `remap-istanbul` reports `Unable to find entry for` every such file, since no source maps are generated for type definition files.

FWIW `@types` are not fully working yet, i.e. I tried to `import * as sinon from 'sinon';` and it complains about
```
ENOENT: no such file or directory, open 'util'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18) ...
```
while that same import works in Protractor tests. That said, I didn't add any of the `node_modules` explicitly in Karma config or `tsconfig`.

Were you able to further troubleshoot performance issues mentioned in [#13](https://github.com/monounity/karma-typescript/issues/4#issuecomment-252541433)? I don't have any big projects yet, so haven't noticed much overhead (maybe there's just a slight one).

**Comment by dinvlad** [comment]
Actually, it's more appropriate to exclude `.d.ts` from `remapOptions`:
```
remapOptions: {
  exclude: /\.d\.ts/,
}
```
This way, changes to `.d.ts` files will still be tracked, and any Typescript errors would still be caught by Karma.

**Comment by dinvlad** [comment]
Hmm.. with that, errors in `.d.ts` do get reported as `[compiler.karma-typescript]: ... TSxxxx: `, however tests are still being run and report success. May that be because all sources are still emitted for other files? But if I set `"noEmitOnError": true` in `tsconfig`, karma just fails immediately with "exit code 1".

**Comment by dinvlad** [comment]
Also, I have to include `.spec.ts` files in `tsconfig` now, however that breaks other utilities, such as Webpack. I understand there might be a conflict between `include` in `tsconfig` and in Karma config, however it seems that the plugin should favor settings in the latter and just ignore that section in `tsconfig`. This approach provides a better separation of concerns IMO.

**Comment by dinvlad** [comment]
Requiring `spec` files to be included in `tsconfig` is a breaking change IMO. I.e. my Webpack becomes completely unusable because of its a bug in `ts-loader` that tries to process everything that is specified in `tsconfig`, including the `spec` files, despite the use of filename filters in `webpack.config`.

So it'd be bad for this behavior to be the default in 2.1 - at the very least, we should be able to specify a custom `tsconfig` that would work for it (though then we'd need to keep 2 different `tsconfig`s, one for Karma and one for Webpack). Is there already such an option?

**Comment by monounity** [comment]
@dinvlad, nice work!!

I've fixed some of the bugs:
  * The sinon loading bug is fixed, it required a module from the internal node.js api.
  * *.d.ts files are now excluded from instrumentation by default. It's also possible to customize the exclusion filter in the karma config:

```javascript
karmaTypescriptConfig: {
    excludedFiles: /\.(d|spec|test)\.ts/,
    compilerOptions: {
        sourceMap: true
    }
...
}
```
Regrading the issue with `element.tagName === 'DIV'`, could you give me an example with code? I'm not sure how to reproduce the error.

The performance issues are sorted out! The integration tests with 2000+ files compiles in just seconds on my laptop :)

And last but not least, if we want type checking, types etc from the tsconfig the whole project has to be compiled in one go, so not including the spec files in the tsconfig might take some thought/discussion.

My main goal when creating this plugin was making unit testing with coverage as easy as possible, without jumping through hoops in multiple configuration files... As you suggested, a path to a tsconfig might be a way to solve the problem, I'll have to consider what happens if a tsconfig path isn't provided. Maybe fallback to the same default options as in 2.0.x and using glob to scoop up the files specified in the karma config.

**Comment by monounity** [comment]
@dinvlad, it's now possible to configure a path to tsconfig.json, if it's not set the plugin will fallback to default compiler options.

All karma-typescript config options:
```javascript
karmaTypescriptConfig: {
    tsconfig: "./tsconfig.json",
    compilerOptions: {
        noImplicitAny: true,
        ...
    },
    excludedFiles: /\.(d|spec|test)\.ts/,
    reports:
    {
        "html": "coverage",
        ....
    },
    transformPath: function(filepath) {
        return filepath.replace(/\.(ts|tsx)$/, ".js");
    }
}
```

The default compiler options:
```javascript
{
    compilerOptions: {
        emitDecoratorMetadata: true,
        experimentalDecorators: true,
        jsx: "react",
        module: "commonjs",
        sourceMap: true,
        target: "ES5"
    },
    exclude: ["node_modules"]
}
```

The default options should take care of common scenarios like plain Typescript, Angular2, React, Typescript v1.6, v1.7, v1.8, v2.0 etc

This means you should be able to use your project tsconfig with webpack and run karma-typescript with the default options. If the default options aren't enough you can add/override options in the Karma config.

**Comment by PhillipBerger-BSFT** [comment]
@g00fy- Does your example with custom paths defined in `tsconfig.json` actually work?  See my issue here: https://github.com/monounity/karma-typescript/issues/43
