### ISSUE TITLE
plugin should follow karma-plugins installation example

### ISSUE THREAD

**Issue by moshmage** [monounity/karma-typescript#50]
There's a missing Karma dependency, both in package.json and in the documentation. It's just a minor thing, but it can put new devs behind.
Since the Karma Plugin way is of not depending on karma on package, text should be changed to `npm install karma karma-typescript --save-dev`

*edit: There's also the missing karma-jasmine and jasmine-core. I'm thinking all these should be set as `peerDependencies` instead of dependencies as the user will be warned if they are missing*

**Comment by erikbarke** [comment]
Hey @moshmage, great suggestion! These are the dependencies listed in the package.json of the [default example project](https://github.com/monounity/karma-typescript/tree/master/example-project):

```json
"dependencies": {
  "@types/jasmine": "^2.5.35",
  "jasmine-core": "^2.4.1",
  "karma": "^1.2.0",
  "karma-chrome-launcher": "^2.0.0",
  "karma-cli": "^1.0.1",
  "karma-jasmine": "^1.0.2",
  "karma-typescript": "../",
  "typescript": "latest"
}
```

Maybe the text should be changed to something like `npm install @types/jasmine jasmine-core karma karma-chrome-launcher karma-cli karma-jasmine karma-typescript typescript --save-dev`, thoughts?

I'm a bit reluctant adding `jasmine` as a peer dependency as there are devs using this plugin with `mocha` too.

**Comment by moshmage** [comment]
> I'm a bit reluctant adding jasmine as a peer dependency as there are devs using this plugin with mocha too.
True, `jasmine-core` and `mocha` shouldn't be listed as dependencies (as the plugin shouldn't depend on a framework for the state reason)

the install text can be only `npm install --save-dev karma karma-typescript` as, like jasmine/mocha, devs can use phantomJS instead of Chrome as their browser plugin; karma-cli is already depended by karma, so no use having it listed on the install

**Comment by erikbarke** [comment]
So the installation part of the readme would look like this:

## Installation and configuration

First, install the plugin:

`npm install karma karma-typescript --save-dev`

Then put this in your Karma config:

```javascript
frameworks: ["jasmine", "karma-typescript"],

files: [
    { pattern: "src/**/*.ts" }
],

preprocessors: {
    "**/*.ts": ["karma-typescript"]
},

reporters: ["progress", "karma-typescript"],

browsers: ["Chrome"]
```

Only specifying `karma karma-typescript` might be confusing, since the Karma config example uses jasmine and Chrome...

The [package.json](https://github.com/karma-runner/karma/blob/master/package.json) of Karma doesn't list `karma-cli` as a depencency and the current [karma plugin documentation](http://karma-runner.github.io/1.0/config/plugins.html) says `npm install karma-<plugin name> --save-dev`.

How about this:

## Installation and configuration

First, install the plugin:

`npm install karma-typescript --save-dev`

Then put this in your Karma config:

```javascript
frameworks: ["jasmine", "karma-typescript"],

files: [
    { pattern: "src/**/*.ts" }
],

preprocessors: {
    "**/*.ts": ["karma-typescript"]
},

reporters: ["progress", "karma-typescript"],

browsers: ["Chrome"]
```

To install all the modules needed to run the above eaxmple:
`npm install @types/jasmine jasmine-core karma karma-chrome-launcher karma-cli karma-jasmine karma-typescript typescript --save-dev`

**Comment by moshmage** [comment]
> To install all the modules needed to run the above eaxmple:
npm install @types/jasmine jasmine-core karma karma-chrome-launcher karma-cli karma-jasmine karma-typescript typescript --save-dev

could be

> To run the configuration above you need the following npm modules installed
- [@type/jasmine]()
- [jasmine-core](https://jasmine.github.io/)
- [karma-chrome-launcher]()
- karma-typescript
- [karma-cli](https://github.com/karma-runner/karma-cli)
- [karma](http://karma-runner.github.io)
- [typescript]()

ps: some links might not work; But the idea is there.

**Comment by erikbarke** [comment]
Awesome! Would you like to add this in a pull request and get contributor credit or should I add it? I'm happy either way, just let me know!

**Comment by moshmage** [comment]
[looks like this](https://gist.github.com/moshmage/215926a956478d4fdb47be18659c9807) :)
