### ISSUE TITLE
How to get karma-typescript to work with react-css-modules?

### ISSUE THREAD

**Issue by rfgamaral** [monounity/karma-typescript#66]
I'm not sure if this is any issue with `karma-typescript`,  [`enzyme`](https://github.com/airbnb/enzyme) or [`react-css-modules`](https://github.com/gajus/react-css-modules). Or if there's something I need to do with any of those tools to be able to test CSS modules.

Here's a very simple component with tests demonstrating the issue:

**Hello.tsx:**

```typescript
import * as React from "react";
import * as ReactCSSModules from "react-css-modules";

import * as helloStyle from "./Hello.css";

@ReactCSSModules(helloStyle)
export default class Hello extends React.Component<any, any> {
    render() {
        return <div styleName="color">Hello World</div>;
     }
}
```

**HelloSpec.tsx:**

```typescript
import * as React from "react";
import * as ReactCSSModules from "react-css-modules";

import * as chai from "chai";
import * as chaiEnzyme from "chai-enzyme"

import { expect } from "chai";
import { shallow } from "enzyme";

import Hello from "./Hello";

describe("Hello", () => {

    chai.use(chaiEnzyme());

    let hello = shallow(<Hello />);

    it("should render correctly", () => {
        expect(hello).to.have.tagName("div");
    });

    it("should have correct prop values", () => {
        expect(hello).to.have.text("Hello World");
    });

});
```

And this is the error I get:

> START:
> PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
>   Error: "color" CSS module is undefined.
>   at C:/Users/Amaral/AppData/Local/Temp/karma-typescript-bundle-14232TTFax3aHxeHP.js:7734

This is preventing me from testing anything in my app and I can't find much information about it and how to fix it... Do you think it's anything related to `karma-typescript`? If so, how to fix it?

**Comment by erikbarke** [comment]
Ok, I'll have to add (at least basic) support for css modules, I'll keep you posted 😃

**Comment by rfgamaral** [comment]
Cool, thanks a lot :)

But have you investigated this and concluded it's something missing from `karma-typescript` or the problem could be some other module?

**Comment by erikbarke** [comment]
It's missing from `karma-typescript`, so thanks for reporting this!

**Comment by rfgamaral** [comment]
I think the issue is no entirely related to CSS Modules per se, but how `karma-typescript` handles CSS files importing. I did a simple test for this:

**Hello.css:**

```css
.color {
    color: red;
}

```ts
import * as helloStyle from "./Hello.css";
console.log(helloStyle.color); // undefined
```
The output should have simply be `color` (or with CSS Modules enabled, something like `Hello_color_1ez19`). So the problem is the "import" which returns nothing and everything is undefined.

Makes sense?

**Comment by erikbarke** [comment]
Yeah, it makes sense, right now the plugin only exports a plain old string with the css content inside, so no sweet property goodness like `style.myColor`. This should print the content of the stylesheet:

```javascript
import * as helloStyle from "./Hello.css";
console.log(helloStyle);
```

If you want to take a look, [here's the offending line of code](https://github.com/monounity/karma-typescript/blob/2.1.7/lib/bundler.js#L137).

I'm thinking of hooking up [postcss](https://github.com/postcss/postcss) or some plugin using the `postcss` api to get this working, thoughts?

**Comment by rfgamaral** [comment]
Yes, that prints the whole CSS file... :(

Honestly, I'm not sure what the best course of action would be to fix this. Would that postcss hooking/plugin be transparent for users or would it need additional configuration on `karma.conf.js`? I'm already using postcss so that wouldn't be an issue for me though.

I don't know exactly how `karma-typescript` works but don't you use `webpack.config.js` internally? Can't you just use whatever loaders are defined there so when `karma-typescript` post processes the files, it would just use the appropriate loaders matching CSS files?

**Comment by erikbarke** [comment]
The plugin uses a custom `Browserify` tool chain, not `webpack` for bundling! This is partly because Typescript has already done the grunt work creating an AST and resolving dependencies, it felt unnecessary to waste cpu cycles on doing all that again in the bundling step, and partly because I wanted to preserve the file structure of the project when debugging, so all project files are served standalone by `Karma`, they're not bundled, only wrapped in a tiny loader function.

I'm thinking it should be transparent as a default, it should be as easy as possible running the tests without worrying too much about what happens under the hood, it should Just Work&trade; 😃

**Comment by rfgamaral** [comment]
Agreed :)

You've been very helpful with me these past few days and I should know better than to ask this question but do you have an ETA for fixing this issue or it's not as easy as one might think?

I'm only asking this because I kinda have a deadline for this and it will be really bad if I show up with unit tests 🤣 . But I don't want to put pressure on you man, I'm sure you have a life and other priorities. I'm just asking so I know what to expect and perhaps prepare a "workaround" on my end so I don't show up "empty-handed".

Keep up the good work ;)

**Comment by erikbarke** [comment]
Heh, *real life* is scheduled to hit in just a few days for me, so I really don't want to make any promises here... If I were you I would prepare that workaround, this will take some work to implement, for starters there's a bunch of code that needs to be refactored to be async before I can add support for css modules, but I'll keep you posted here 😃

**Comment by erikbarke** [comment]
@rfgamaral, I have a solution now, using the new bundler transforms API (in 3.0, currently in beta on npm):

```js
karmaTypescriptConfig: {
    bundlerOptions: {
        transforms: [
            function(context, callback) {
                if(context.module === "./Hello.css") {
                    context.source = "module.exports = { myColor: red };";
                    return callback(undefined, true);
                }
                return callback(undefined, false);
            }
        ]
    }
}
```

During the bundling phase, each file is piped through the array of asynchronous functions in `karmaTypescriptConfig.bundlerOptions.transforms[]` and since your code expects `import * as helloStyle from "./Hello.css";` to an object literal, the transforming function simply returns an object literal, `{ myColor: red }` for the module `./Hello.css`.

Pros: it's flexible and easy to implement.
Cons: it's "disconnected" from the actual style sheet and duplicates its properties.

The good news is the new bundler transforms API opens up the possibility of creating a more generic solution for Css Modules, like these `karma-typescript` plugins that provide support for bundling ES6 modules and using relative urls in Angular2 components:

[karma-typescript-es6-transform](https://github.com/monounity/karma-typescript-es6-transform)
[karma-typescript-angular2-transform](https://github.com/monounity/karma-typescript-angular2-transform)

A plugin like should be created and maintained as a separate npm package, any takers?
