### ISSUE TITLE
Shouldn't it be possible to specify only test files for loading instead of tests/source?

### ISSUE THREAD

**Issue by rfgamaral** [monounity/karma-typescript#67]
When I first configured my project for testing I followed this [guide](https://medium.com/@fay_jai/getting-started-on-testing-with-typescript-reactjs-and-webpack-a45a72f4f603#.xnphdbpjz). It worked, for the most part. But when I wanted proper coverage and all that, that's when I moved to `karma-typescript`.

On that guide though, one **only** specifies test files to be loaded and post-processed:

```
files: ["test/**/*.tsx"],
preprocessors: {"test/**/*.tsx": ["webpack"]},
```
The same approach doesn't seem to work with `karma-typescript`. If a test file imports something from the source, it complains that the module cannot be found (because it was not included?). Is this something by design or just a side-effect or how `karma-typescript` works.

Would it make sense to filter just the spec/test files to be loaded and post-processed?

**Comment by erikbarke** [comment]
This is by design! As I mentioned in our discussion in #66, all project files are served standalone by Karma to preserve the file structure when debugging, only npm modules are bundled. If you run your tests in Chrome and hit the big debug button and open the developer tools you will see all your files organized just like they are in your file system.

**Comment by rfgamaral** [comment]
Ok, I understand :)

I only asked this because my Karma setup is taking a while to startup (tests do run pretty fast though) and was wondering if this could be the cause. But on a second thought, it can' be that because I only have a dozen files.

Thanks.
