### ISSUE TITLE
Compiler cant find imported files with different Capital letters in the path

### ISSUE THREAD

**Issue by sagiweis** [monounity/karma-typescript#71]
Hey,
I was trying to add karma-typescript to my project and after almost 2 days of having trouble with it, i noticed something that i think needs to be fixed.

The karma-typescript compiler cant find the source file of an imported ts file if the import path is not exactly as the path to the file - but only different in a capital letter. for example, i downloaded the exmaple-project from the repository and changed the second import in the spec file to be:

`import { HelloComponent } from "./hello.Component";`
instead of 
`import { HelloComponent } from "./hello.component";`

(notice the difference in the letter 'c' in the word 'component')

in this case the compiler will throw the following error:
`ERROR [karma]: Error: No source found for C:/Users/Sagi/Desktop/karma-typescript-master/example-project/src/hello.component.ts!
Is there a mismatch between the Typescript compiler options and the Karma config?`

although IDE's (webstorm for example) will ignore the difference and wont raise any errors.

Thank you.

**Comment by erikbarke** [comment]
Hey @sagiweis, this would affect both the compiler and bundler, but it's definitely doable!

**Comment by cyberhck** [comment]
I don't think this should be labelled as bug, if the filename is wrong, it shouldn't import, we don't want any magic to happen do we? Windows might be case insensitive, but most of CIs are linux based OS. Since `hello.Component` and `hello.component` are two different files, I would say we shouldn't do any magic in there.

**Comment by erikbarke** [comment]
@cyberhck, I agree we should stay away from this type of magic! Also, I'm not sure it would even be possible since there are a lot of third party libraries involved which may or may not play nice with uppercase/lowercase strings internally... My plan at the moment is catching this early in the compiling step and throw a descriptive error if the filename and the imported module name don't match.

**Comment by cyberhck** [comment]
@erikbarke Yes that sounds good, just including it's case sensitive should be enough. Hey, on the same note, when do you think you'll be hitting a stable and out of beta? Do you have any other issues to close?

**Comment by erikbarke** [comment]
Ok, the dependency walker now validates required modules and throws an error pointing out where the filename and the module name differ.

There are a few things left to implement before the next release, but I hope I'll be able to get things ready within a week or two now!

**Comment by cyberhck** [comment]
@erikbarke I see we have a new beta release, are there any outstanding issues which needs to be closed before you release stable one? I've been using beta for a while and it's working perfectly, haven't encountered any issues yet.

**Comment by erikbarke** [comment]
@cyberhck, this is exactly what I want to hear 😄 This release is ready now and it's actually down to putting the finishing touches on the documentation, so it will probably be published within a few days!
