### ISSUE TITLE
config.coverageOptions.exclude.test is not a function

### ISSUE THREAD

**Issue by sir-marc** [monounity/karma-typescript#85]
Heyo :D
I just had the need to exclude multiple files from coverage and saw, that karma-typescript does not support an array on `config.coverageOptions.exclude`.
I think this functionality could be added rather easily or am I wrong?
If you think this would be nice, let me know if I could do that and submit a PR.
It would be a pleasure for me to help you a little bit, because i love your module and you're always really helpful!

**Comment by fchiumeo** [comment]
I use the pipe(|) for add exclusion

```
karmaTypescriptConfig: {
            coverageOptions: {
                exclude: /\.(d|spec|test)\.ts|karma.shim.ts/
            }
}
```

**Comment by sir-marc** [comment]
Oh nice, thank you!
But I think this addition would still make sense

**Comment by erikbarke** [comment]
@sir-marc: a PR, yes please! Create it in the 2.1.8 branch and dig in 👍

**Comment by erikbarke** [comment]
@sir-marc, just to clarify:
- We need to let users specify either a regex or an array of regexes, as to not break existing configurations
- To test if the configured value is an array, add [lodash.isarray](https://www.npmjs.com/package/lodash.isarray) to the project
- The configured value(s) should be validated and an informative error message should be thrown if any of the values isn't a regex object
- The project is linted and integration tested on Travis and Appveyor, make sure you can run `npm run lint` and `npm test` (osx, *nix) or `ci\run.bat` (windows) in the root of the project before checking in

Don't worry too much about the Appveyor build, the Karma Chrome launcher frequently crash and burn, I have no idea why yet... As a workaround, I just rerun the build until it passes 😷

**Comment by sir-marc** [comment]
@erikbarke Yeah I've implemented it just like that, so existing config won't breake.
I've used `instanceof Array`, would you prefer lodash?
Yes, the tests work just fine, but do you have unittests?
Because I've added two methods to check this. So should I test them anywhere?
And as those methods are more like utils method, i could extract them, but I don't see any other utils, so should I let them inside the method?

**Comment by erikbarke** [comment]
@sir-marc, oops, didn't do my homework on that one, just use `Array.isArray` instead of ` lodash.isarray`!

There are no unit tests (seems a bit self-contradictory doesn't it...) since the integration tests run `karma-typescript` to test itself. However, `lib/configuration.js` (which is where I guess you've added the validation of the regex/array type) should be easy to unit test since it doesn't require any modules, it's completely separated from the rest of the code.

The checks inside the bundler would be hard to integration test in a meaningful way if we want to test that both a regex and an array of regexes work, so I guess it's time to add proper unit tests...

That linting error is weird, it works on my laptop (OS X), on Travis, Appveyor... What OS are you on?

**Comment by sir-marc** [comment]
Ok, i can just switch my code to Array.isArray, no problem.
Ehm I've added the code directly inside the `coverage.js` file, as there is the point where it's used.
So should I separate it into a separate file, so you could use this method elsewhere (and because it doesnt really belong to the coverage file) and write unit test or should i let it be, where it is and write no unit tests, as it should be tested with the integration tests? (which should also extend to test the array)

**Comment by erikbarke** [comment]
Moving to #86
