### ISSUE TITLE
Bug on latest 2.1.8?

### ISSUE THREAD

**Issue by paibamboo** [monounity/karma-typescript#89]
Something is wrong with the latest 2.1.8. 
I did a fresh npm install on my project, run test, and got this error at fixWindowsPath().

![replace-undefined](https://cloud.githubusercontent.com/assets/13611391/22871106/61b366a6-f1e0-11e6-8119-6eb331853a37.png)

So I did npm install from a specified commit around 14 days ago, it works well.

**Comment by erikbarke** [comment]
Hey @paibamboo, this is not a bug, it's a feature 😉 The API has changed a bit and `karmaTypescriptConfig.bundlerOptions.exclude` now does what the name implies, it excludes modules from the bundle without mercy! It's sibling, the option `karmaTypescriptConfig.bundlerOptions.ignore` is a bit more lenient and replaces the source with and empty object, `module.exports={};`.

I've updated the config in #75 and moved the webpack stuff to `karmaTypescriptConfig.bundlerOptions.ignore` and now your project runs just fine with the latest 2.1.8!

Maybe 2.1.8 should be a 2.2 or even a 3.0 since there are breaking changes... I should also add a more informative error message if an excluded module is required from code that's actually executed, so I'll keep this issue open.

**Comment by erikbarke** [comment]
Hmm, maybe a better solution would be to simply remove lines 30-47 in server.tsx, `if (process.env.NODE_ENV !== 'production') { ...` since you don't need `webpack` for running your tests now. If that's case you can also safely remove the ignored modules from the Karma config.
