### ISSUE TITLE
Handling shared JS source in testing

### ISSUE THREAD

**Issue by ernieturner** [monounity/karma-typescript#90]
I have a setup where I've got a shared directory of files that are used in both my Typescript web app and my non-Typescript NodeJS backend. These shared files are written in CommonJS style format and have `.js` file extensions. In order to include them from my Typescript app I had to set the `allowJs` directive in the compile and I can successfully import them within my Typescript files. So far so good.

However, I can't seem to figure out how to configure `karma-typescript` to get it to run successfully with this setup. During the compiling process, when it comes across these files I get an error that says:

```
[compiler.karma-typescript]: error TS5055: Cannot write file '.../common/Urls.js' because it would overwrite input file.
```
Which then causes a handful of other cascading errors that cause the unit tests to fail. The files in the `common` directory show up in both the `preprocessor` and `compiler` sections when looking at debug logging and this error shows up after the end of the `compiler` phase.

 Is there anyway to support this use case?

**Comment by erikbarke** [comment]
Hey @ernieturner, what does your `.js` files look like, could you post an example here?

**Comment by ernieturner** [comment]
Sure, here's an example of one

```
const Urls = require('./Urls');

module.exports = {
    list(authToken, parameters){
        return {
            method: 'POST',
            url: Urls.Vendor.create,
            headers: {
                Authorization: `token ${authToken}`
            },
            data: parameters
        };
    },

    create(authToken, parameters){
        return {
            method: 'POST',
            url: Urls.Vendor.create,
            headers: {
                Authorization: `token ${authToken}`
            },
            data: parameters
        };
    }
};
```

And I'm just including that file from my TypeScript files like `import * as VendorApi from '../../api/Vendor';`

**Comment by erikbarke** [comment]
Thanks! I have an integration test now with your example that produces the same Typescript error "...because it would overwrite input file". The test passes in Chrome if I don't add the javascript files in the Karma config, they're automatically included in the main bundle since they're non-Typescript resources.

I'll try to get rid of the "...because it would overwrite input file" error!

**Comment by ernieturner** [comment]
Thanks! Let me know if you need any help testing it out if you're able to find a fix. I can pull down a branch and use it on my local setup if need be.

**Comment by erikbarke** [comment]
The "...because it would overwrite input file" error is gone now, and your example works in Chrome but not in PhantomJS because your code is with ES6 syntax. I'm working on ES6 transpiling support, let me know if you need it!

If you want to try it out, you can install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.8`.

**Comment by ernieturner** [comment]
Ahh, I hadn't put it together that the subsequent errors I was getting was for the ES6 syntax, not because of the overwrite error. That makes a lot of sense now.

Pulled down that dev branch, reverted my common files to use ES5 syntax and everything works great! Thanks for the help here. I'll definitely keep an eye on things here for when ES6 syntax is added so I can move those shared files back to that syntax. Thanks again!
