### ISSUE TITLE
Uncaught ReferenceError: exports is not defined with Typescript 2.2.1

### ISSUE THREAD

**Issue by dnasir** [monounity/karma-typescript#94]
Everything was working just fine until I decided to update my Typescript version to the latest one. Then I started getting the following error.

    Uncaught ReferenceError: exports is not defined

You can reproduce this bug by creating a new project and setting ``"typescript": "^2.2.1"`` in your ``package.json`` and running some unit tests. The above error should show up in your terminal.

I'm guessing there's probably some breaking changes from TS 2.1.x to 2.2.x that this package needs to accommodate.

**Comment by erikbarke** [comment]
Hey @dnasir, a lot of things broke with typescript@2.2.1 and have been fixed in the 2.1.8 dev branch, please see #92!

Does it work for you if you install from the latest dev branch, npm install https://github.com/monounity/karma-typescript.git#2.1.8?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by dnasir** [comment]
@erikbarke Hi. Sorry I didn't see that the issue was already reported. Feel free to close this one.

Also, I can confirm that version 2.1.8 works with TS 2.2.1. At least it is for me.
